version: 0.2

phases:
 pre_build:
  commands:
   - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login  --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

 build:
  commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t ${IMAGE_REPO_NAME} .
    - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
    # AWS CLI v2 をインストール
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
    - unzip -q awscliv2.zip
    - ./aws/install --bin-dir /root/.pyenv/shims --install-dir /usr/local/aws-cli --update

post_build:
  commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
